### ISSUE TITLE
มี template ของ reports ของระบบหรือไม่ 

### ISSUE THREAD

**Issue by pojii** [we-inc/mms-the-yellow-stone#5]
มี template ของ reports ของระบบหรือไม่
	-ไม่มี

**Comment by 5731045421-TA** [comment]
ได้เพิ่ม templete การชำระเงินเข้ามา
![image](https://user-images.githubusercontent.com/13790760/32653599-fbb67746-c63a-11e7-846e-8377b6db7e1d.png)
