### ISSUE TITLE
Class diagram และ ER สะท้อนถึงระบบได้ครบถ้วน และถูกต้อง ตาม requirements ของระบบหรือไม่ -Class diagram ควรใส่ชื่อความสัมพันธ์รวมถึงใส่ลูกศรบอกทิศทาง

### ISSUE THREAD

**Issue by pojii** [we-inc/mms-the-yellow-stone#7]
Class diagram และ ER สะท้อนถึงระบบได้ครบถ้วน และถูกต้อง ตาม requirements ของระบบหรือไม่
-Class diagram ควรใส่ชื่อความสัมพันธ์รวมถึงใส่ลูกศรบอกทิศทาง

**Comment by 5731045421-TA** [comment]
![rentory](https://user-images.githubusercontent.com/13790760/32653303-007bb45e-c63a-11e7-8f51-7e007cd565f6.jpg)

**Comment by pojii** [comment]
Good job
